<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWAnJRAz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWAnJRAz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWAnJRAz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWAnJRAz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWAnJRAz\App_KernelDevDebugContainer([
    'container.build_hash' => 'WAnJRAz',
    'container.build_id' => '6edeacd9',
    'container.build_time' => 1653050409,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWAnJRAz');
