<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNCaO5Ox\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNCaO5Ox/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNCaO5Ox.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNCaO5Ox\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNCaO5Ox\App_KernelDevDebugContainer([
    'container.build_hash' => 'NCaO5Ox',
    'container.build_id' => '5a7dba78',
    'container.build_time' => 1653051386,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNCaO5Ox');
