<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOOR136N\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOOR136N/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOOR136N.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOOR136N\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOOR136N\App_KernelDevDebugContainer([
    'container.build_hash' => 'OOR136N',
    'container.build_id' => '5354f840',
    'container.build_time' => 1653058333,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOOR136N');
